# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01eef992e93f6d10075c51cbbccddc18572fd0d0433adf4653fd4c9b070401e72c3f78b1635e99d8ebb4feb35100afa5b7c82bd824374bebb4fc51e7b711de6d

test:
  secret_key_base: 362c3bb670f486a0ea5f44ca2266c39b75b2480f5519baec98cbac929cca5603c953de3eb25ba2514dafa6562295ed0494442ebbfa403a5fd1d18288762573be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
